### ISSUE TITLE
Message improperly decoded

### ISSUE THREAD

**Issue by PawelPacholek** [schnack/pdu_sms#1]
Hello,

I have the following PDU:

07912470338016004404B9643000118120510104414071050003EE03036839D072CC02C1DFEB3A19847E83DC65BDBC3E4FD3CB20F87BCE0EBBD36DD0942A2D069B4F278808728741341B6CE60259D3E332C81D06DDEF7717BDD57E8BD3ECB26BAC7FCDE9F272B8FD76BB40D6F01C446D35DFE234BBAC00814020

After decoding, all sms properties look fine apart from the message, which is the following:

"hr@GY@`_WkIAP_A\KuekgSiKA`_gYC]S[A&)%AA\CAhl`f\@,SGKA\CAnoo]h[Z_ESYK]Fu_fieKC[_]]@,CgA([_ESYK@@@@"

I suppose that there is no error in PDU, because much better message can be obtained when decoding here: https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/

I have checked that I am using the latest version of pdu_sms - 1.0.4.

I would be very grateful for fixing this bug.

**Comment by schnack** [comment]
Thank you for contacting us! Bug fixed in version 1.1.1

**Comment by PawelPacholek** [comment]
Now it works well. Thank you very much :-)
