### ISSUE TITLE
ArgumentError: Phone number is invalid

### ISSUE THREAD

**Issue by PawelPacholek** [schnack/pdu_sms#2]
Hello again,

I have the following PDU:

07912470338016000412D0D3751D9E7687414B2100008130109014244061CDB7BA2C0CBBD7611D082A4FA3D9E179D99D0691DFA0309C9D5E87C7E51D881CA6D7DBA030681C9EEB40B0980B3673C960311C0896D3D162BA996D070AD6E96F795A1F1EBBD3A069730A5ABFC93A50AC3603E56635

When trying to decode with the latest version of "pdu_sms" (1.1.1), I get the following error:

 ArgumentError: Phone number is invalid
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.1/lib/pdu_sms/phone.rb:82:in `_set_hex_type_and_phone'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.1/lib/pdu_sms/originating_address.rb:45:in `_set_pdu_hex'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.1/lib/pdu_sms/originating_address.rb:6:in `initialize'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.1/lib/pdu_sms/originating_address.rb:17:in `new'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.1/lib/pdu_sms/originating_address.rb:17:in `decode_sc'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.1/lib/pdu_sms/packet_data_unit.rb:80:in `decode_sc'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.1/lib/pdu_sms/packet_data_unit.rb:92:in `decode'

The PDU itself is correct, because it can be decoded here: 
https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/

It looks like the correct value of 

PduSms::PacketDataUnit.decode(pdu).get_phone_number

should be equal to "Skupina KB".

I would be very grateful for fixing this bug in the next version of "pdu_sms"

**Comment by schnack** [comment]
Please upgrade to version 1.1.2
Fixed a bug in the regular expression.

**Comment by PawelPacholek** [comment]
It works.

I am surprised by such a quick fix  :-)

Thank you very much once again.

**Comment by PawelPacholek** [comment]
Hi again,

Unfortunately, I have another PDU with the same error:

07919712690000F1400BD0C3E4322235020008813051916402218C050003B70301042304320430043604300435043C044B0435002004380437043104380440043004420435043B043800210020003100380020043C04300440044204300020002D00200432044B0431043E0440044B0020041F044004350437043804340435043D0442043000200420043E0441044104380438002E00200413043E043B043E0441043E04320430

After decoding here:
https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/
I found that this time method "get_phone_number" should return "CIK_RF".

Thank you in advance for fixing this in the next version of your gem.

**Comment by schnack** [comment]
The error fixed in 1.1.6

In the PDU in the sender's "CIK_RF" number, instead of a space, the ASCII character 17 (DC1 - Device control 1)

**Comment by PawelPacholek** [comment]
It works :-)

Thank you very much once again.
