### ISSUE TITLE
ArgumentError: The message is too long

### ISSUE THREAD

**Issue by PawelPacholek** [schnack/pdu_sms#3]
Hello again,

This time I have the following PDU:

07912470338016004404B96430001181301190404340A0050003CE0201886FB13C0F2297DD2C903E0C9A81C8EE3CC81A6E83DC61D0383D6797413618ED668BD96035D07CFD768FD3A037B95D768741FA3088FC16A7E969D0B40E2FCB41F3B05E1C76819A757D995E06CDD320751A14669741737798EC7E83F4E17919A40FC3DDEF3ADD055286D73FD0941E1EA741F33488FC16A7E9A0B5BC4C4ED341F0375D5E16BBDF

Decoding attempt produces the following error in the latest version of your gem (1.1.2):

ArgumentError: The message is too long
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.2/lib/pdu_sms/user_data.rb:196:in `_check_message'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.2/lib/pdu_sms/user_data.rb:12:in `initialize'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.2/lib/pdu_sms/user_data.rb:104:in `new'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.2/lib/pdu_sms/user_data.rb:104:in `decode_sc'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.2/lib/pdu_sms/packet_data_unit.rb:85:in `decode_sc'
    /home/pawelpacholek/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pdu_sms-1.1.2/lib/pdu_sms/packet_data_unit.rb:92:in `decode'

The given PDU can be decoded here:
https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/

As usually, I will be very grateful for fixing this bug in the next version of this gem.

**Comment by schnack** [comment]
Добрый день!
Исправлено в версии 1.1.4.
Ошибка в проверке длины сообщения в 7 битной кодировке. 
Спасибо за обращение.

**Comment by PawelPacholek** [comment]
Hello,

It works now in version 1.1.5. Thank you very much once again.
