### ISSUE TITLE
ArgumentError: invalid value for Integer(): "08"

### ISSUE THREAD

**Issue by PawelPacholek** [schnack/pdu_sms#4]
Hello again,

For the following PDU: 07918497908906F0040DD042ED55B894D1000000813062611125802BCCF7F97D0FBBD36590CCE682CD5C32580C078AD974B11868DE9E2FDF641D2816A3D96E34DC0C

I receive the following error:

ArgumentError: invalid value for Integer(): "08"
  from pdu_sms/service_center_time_stamp.rb:64:in `%'
  from pdu_sms/service_center_time_stamp.rb:64:in `_absolute_pdu'
  from pdu_sms/service_center_time_stamp.rb:43:in `get_time'

Please, fix it in the next version.

**Comment by schnack** [comment]
Ready! v1.1.7

**Comment by PawelPacholek** [comment]
Hi,

It works! Excellent and quick job. Thank you very much one more time :-)
