### ISSUE TITLE
Some characters are not properly decoded

### ISSUE THREAD

**Issue by PawelPacholek** [schnack/pdu_sms#5]
Hello,

I have the following PDU:

07918497908906F00414D0C3343D3D8597C7E9301B000081707261153280A0C3343D0D4286DD64F6FB9ED781926EF35BDEAEABCBED3CE80DAACBEB63F4BB9D2EBBD375105CFE3ECBC3ED3AA8199ED3CBF271584E0641E5E971995D9ECF415378799C0EB3E72E10F1CD0E8FF520F21B3483B9603950589C07BDC965B13C3C0689D3EC321D447E83D66977D8059AC2E5E13B590F42D3E970DDEB354ED3D3AE76F9056546A0F2F4B8CC2ECFE7

After decoding, all sms properties look fine apart from the message, which contains the "\u0011" character:

"Citi Handlowy: Informujemy o uruchomieniu programu Mastercard Priceless Specials. Dolacz do 30.09 aby odebrac bilet do kina. Sprawdz http://citi.me/PL\u0011Priceless"

When decoding here: https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/
I get the same message, but with the underscore "_" instead of the  "\u0011" character.

I have checked that I am using the latest version of pdu_sms - 1.1.7.

I would be very grateful for fixing this bug.

**Comment by schnack** [comment]
I do not see a problem in the sms_pdu library 1.1.7

The text of the message actually contains a symbol "\u0011"

Test source:
```
#!/usr/bin/env ruby

require "pdu_sms"

pdu = '07918497908906F00414D0C3343D3D8597C7E9301B000081707261153280A0C3343D0D4286DD64F6FB9ED781926EF35BDEAEABCBED3CE80DAACBEB63F4BB9D2EBBD375105CFE3ECBC3ED3AA8199ED3CBF271584E0641E5E971995D9ECF415378799C0EB3E72E10F1CD0E8FF520F21B3483B9603950589C07BDC965B13C3C0689D3EC321D447E83D66977D8059AC2E5E13B590F42D3E970DDEB354ED3D3AE76F9056546A0F2F4B8CC2ECFE7'
puts ''

msg = PacketDataUnit.decode(pdu).get_message
puts msg
PacketDataUnit.decode(pdu).get_message.unpack("U*").each_with_index do |v, i|
  puts "#{msg[i]} - #{'\u%04X' % v}"
end
```
Result:
```
Citi Handlowy: Informujemy o uruchomieniu programu Mastercard Priceless Specials. Dolacz do 30.09 aby odebrac bilet do kina. Sprawdz http://citi.me/PLPriceless
C - \u0043
i - \u0069
t - \u0074
i - \u0069
  - \u0020
H - \u0048
a - \u0061
n - \u006E
d - \u0064
l - \u006C
o - \u006F
w - \u0077
y - \u0079
: - \u003A
  - \u0020
I - \u0049
n - \u006E
f - \u0066
o - \u006F
r - \u0072
m - \u006D
u - \u0075
j - \u006A
e - \u0065
m - \u006D
y - \u0079
  - \u0020
o - \u006F
  - \u0020
u - \u0075
r - \u0072
u - \u0075
c - \u0063
h - \u0068
o - \u006F
m - \u006D
i - \u0069
e - \u0065
n - \u006E
i - \u0069
u - \u0075
  - \u0020
p - \u0070
r - \u0072
o - \u006F
g - \u0067
r - \u0072
a - \u0061
m - \u006D
u - \u0075
  - \u0020
M - \u004D
a - \u0061
s - \u0073
t - \u0074
e - \u0065
r - \u0072
c - \u0063
a - \u0061
r - \u0072
d - \u0064
  - \u0020
P - \u0050
r - \u0072
i - \u0069
c - \u0063
e - \u0065
l - \u006C
e - \u0065
s - \u0073
s - \u0073
  - \u0020
S - \u0053
p - \u0070
e - \u0065
c - \u0063
i - \u0069
a - \u0061
l - \u006C
s - \u0073
. - \u002E
  - \u0020
D - \u0044
o - \u006F
l - \u006C
a - \u0061
c - \u0063
z - \u007A
  - \u0020
d - \u0064
o - \u006F
  - \u0020
3 - \u0033
0 - \u0030
. - \u002E
0 - \u0030
9 - \u0039
  - \u0020
a - \u0061
b - \u0062
y - \u0079
  - \u0020
o - \u006F
d - \u0064
e - \u0065
b - \u0062
r - \u0072
a - \u0061
c - \u0063
  - \u0020
b - \u0062
i - \u0069
l - \u006C
e - \u0065
t - \u0074
  - \u0020
d - \u0064
o - \u006F
  - \u0020
k - \u006B
i - \u0069
n - \u006E
a - \u0061
. - \u002E
  - \u0020
S - \u0053
p - \u0070
r - \u0072
a - \u0061
w - \u0077
d - \u0064
z - \u007A
  - \u0020
h - \u0068
t - \u0074
t - \u0074
p - \u0070
: - \u003A
/ - \u002F
/ - \u002F
c - \u0063
i - \u0069
t - \u0074
i - \u0069
. - \u002E
m - \u006D
e - \u0065
/ - \u002F
P - \u0050
L - \u004C
 - \u0011
P - \u0050
r - \u0072
i - \u0069
c - \u0063
e - \u0065
l - \u006C
e - \u0065
s - \u0073
s - \u0073
```

![0011](https://user-images.githubusercontent.com/1570762/43393567-510c2298-9400-11e8-9aee-fedc9f6913b6.png)

![_](https://user-images.githubusercontent.com/1570762/43393574-53cf49c4-9400-11e8-839e-2ccdcc6eda29.png)

**Comment by sugar700** [comment]
This is because SMS encoding (GSM 03.38) is not implemented: https://en.wikipedia.org/wiki/GSM_03.38

This encoding is very close to ASCII, but it isn't ASCII.

**Comment by PawelPacholek** [comment]
I agree with xfix.

Moreover, I checked that the main competition (https://github.com/tulak/pdu_tools) returns correct result for this case - with "_" instead of "\u0011"

**Comment by schnack** [comment]
OK. I need time to solve this problem. To my regret, the default ruby does not support the GSM encoding. =(

**Comment by schnack** [comment]
I suggest using https://github.com/yury/gsm_encoder

Test source:
```
#!/usr/bin/env ruby

require "gsm_encoder"
require "bundler/setup"
require "pdu_sms"

include PduSms

pdu = '07918497908906F00414D0C3343D3D8597C7E9301B000081707261153280A0C3343D0D4286DD64F6FB9ED781926EF35BDEAEABCBED3CE80DAACBEB63F4BB9D2EBBD375105CFE3ECBC3ED3AA8199ED3CBF271584E0641E5E971995D9ECF415378799C0EB3E72E10F1CD0E8FF520F21B3483B9603950589C07BDC965B13C3C0689D3EC321D447E83D66977D8059AC2E5E13B590F42D3E970DDEB354ED3D3AE76F9056546A0F2F4B8CC2ECFE7'

msg = PacketDataUnit.decode(pdu).get_message

puts GSMEncoder.decode(msg)
```
Result: 

`Citi Handlowy: Informujemy o uruchomieniu programu Mastercard Priceless Specials. Dolacz do 30.09 aby odebrac bilet do kina. Sprawdz http://citi.me/PL_Priceless`

**Comment by PawelPacholek** [comment]
Thank you for the solution.

Unfortunately, it does not work for the following PDU:

07919712690000F1400BD0C3E4322235020008813051916402218C050003B70301042304320430043604300435043C044B0435002004380437043104380440043004420435043B043800210020003100380020043C04300440044204300020002D00200432044B0431043E0440044B0020041F044004350437043804340435043D0442043000200420043E0441044104380438002E00200413043E043B043E0441043E04320430

The expected message is the following:

Уважаемые избиратели! 18 марта - выборы Президента России. Голосова

The result of using GSMEncoder.decode(msg) is the following:

?????????????????? ????????????????????! 18 ?????????? - ???????????? ???????????????????? ????????????. ????????????????

**Comment by schnack** [comment]
```
#!/usr/bin/env ruby

require "gsm_encoder"
require "bundler/setup"
require "pdu_sms"

include PduSms

pdu = '07919712690000F1400BD0C3E4322235020008813051916402218C050003B70301042304320430043604300435043C044B0435002004380437043104380440043004420435043B043800210020003100380020043C04300440044204300020002D00200432044B0431043E0440044B0020041F044004350437043804340435043D0442043000200420043E0441044104380438002E00200413043E043B043E0441043E04320430'

msg = PacketDataUnit.decode(pdu)

if msg.data_coding_scheme.alphabet_7bit? 
   puts GSMEncoder.decode(msg.get_message)
else
   puts msg.get_message
end

```

**Comment by PawelPacholek** [comment]
OK. It works well now.

Thank you very much.
